#Support Vectors
# Kernels Function --> transform input features into higher dimemsional plane --> separate

In [2]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.svm import SVC

In [3]:
X = np.array([
              [-1,-1],
              [-2,-1],
              [1,1],
              [2,1] 
])

In [4]:
y = np.array([1,1,2,2])

In [5]:
clf = make_pipeline(StandardScaler(), SVC(gamma='auto'))

In [6]:
clf.fit(X,y)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('svc', SVC(gamma='auto'))])

In [7]:
clf.predict([[2,-1]])

array([2])

In [8]:
from sklearn.datasets import load_iris

In [9]:
X,y = load_iris(return_X_y=True)

In [10]:
clf1 = make_pipeline(StandardScaler(), SVC(gamma='auto'))

In [11]:
clf1.fit(X,y)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('svc', SVC(gamma='auto'))])

In [12]:
X[:2]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

In [13]:
clf1.predict(X[130:133])

array([2, 2, 2])