In [2]:
# import the library
import keras



1.   Load data
2.   define keras models
3.   compile
4.   fit / train
5.   evaluate



In [3]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

In [4]:
dataset = np.loadtxt('pima-indians-diabetes.data.csv',delimiter=',')

In [5]:
dataset

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [6]:
X = dataset[:,0:8]
y = dataset[:,8]

In [7]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [8]:
y

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

In [9]:
model = Sequential()

In [10]:
model.add(Dense(12,input_dim=8,activation='relu'))

In [11]:
model.add(Dense(8,activation='relu'))

In [12]:
model.add(Dense(1,activation='sigmoid'))

In [13]:
model.compile(loss='binary_crossentropy')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 12)                108       
                                                                 
 dense_1 (Dense)             (None, 8)                 104       
                                                                 
 dense_2 (Dense)             (None, 1)                 9         
                                                                 
Total params: 221
Trainable params: 221
Non-trainable params: 0
_________________________________________________________________


In [15]:
model.fit(X,y,epochs=150,batch_size=10)

Epoch 1/150
77/77 [==============================] - 1s 2ms/step - loss: 4.5729
Epoch 2/150
77/77 [==============================] - 0s 2ms/step - loss: 1.1170
Epoch 3/150
77/77 [==============================] - 0s 2ms/step - loss: 1.0065
Epoch 4/150
77/77 [==============================] - 0s 2ms/step - loss: 0.8981
Epoch 5/150
77/77 [==============================] - 0s 2ms/step - loss: 0.8571
Epoch 6/150
77/77 [==============================] - 0s 2ms/step - loss: 0.8134
Epoch 7/150
77/77 [==============================] - 0s 2ms/step - loss: 0.7851
Epoch 8/150
77/77 [==============================] - 0s 2ms/step - loss: 0.7629
Epoch 9/150
77/77 [==============================] - 0s 2ms/step - loss: 0.7347
Epoch 10/150
77/77 [==============================] - 0s 2ms/step - loss: 0.7461
Epoch 11/150
77/77 [==============================] - 0s 2ms/step - loss: 0.7160
Epoch 12/150
77/77 [==============================] - 0s 2ms/step - loss: 0.7077
Epoch 13/150
77/77 [=================

In [16]:
model.evaluate(X,y)

24/24 [==============================] - 0s 1ms/step - loss: 0.4989


0.49893298745155334