In [1]:
import numpy as np
from sklearn.decomposition import PCA

In [2]:
X = np.array([
              [-1,-1],
              [-2,-1],
              [-3,-2],
              [1,1],
              [2,1],
              [3,2]
])

In [8]:
pca = PCA(n_components=1)

In [9]:
pca.fit(X)

PCA(copy=True, iterated_power='auto', n_components=1, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [10]:
#explained variance
pca.explained_variance_

array([7.93954312])

In [11]:
pca.explained_variance_ratio_

array([0.99244289])

In [12]:
pca.singular_values_

array([6.30061232])